$('.owl-carousel').owlCarousel({
          stagePadding: 50,
          loop:true,
          margin:20,
          nav:true,
          responsive:{
              0:{
                  items:1
              },
              600:{
                  items:1
              },
              1000:{
                  items:2
              },
              1200:{
                items:2
              }
          }
      })